name: Publish Python ğŸ distributions ğŸ“¦ to PyPI and TestPyPI

on: push

jobs:
  test:
    name: Build and test Python ğŸ
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Test formatting
      run: |
        black --check .
        isort --check .
        docformatter --check -r .
    - name: Test with pytest
      run: pytest .
    - name: Static code analysis
      run: mypy .
    - name: Run pylint
      run: pylint quantuminspire
